services:
  main-service:
    build: main/.
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres-service
      - POSTGRES_DB=main
      - POSTGRES_USER=user123
      - POSTGRES_PASSWORD=user123
    depends_on:
      - sub-service
      - postgres-service

  sub-service:
    build: sub/.
    ports:
      - "9090:9090"

  postgres-service:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=main
      - POSTGRES_USER=user123
      - POSTGRES_PASSWORD=user123